version: '3.5'

services:

   wordpress:
     image: wordpress:latest
     ports:
       - "9999:80" 
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: 12345678
       WORDPRESS_DB_NAME: wordpress
     depends_on:
       - db
     restart: always
     networks:
       - mysql-db

   db:
     image: mysql:5.7 
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 12345678 
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: 12345678
     networks:
       - mysql-db
 
  
   phpmyadmin:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '9998:80'
      networks:
       - mysql-db
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: 12345678  

networks:
  mysql-db:
       